/* ═══════════════════════════════════════════════════════════════════════════
   bt-bank.js — THE BRAIN-TEASER BATTLE BANK
   Every text-solvable question from "B.T.-OF-MATHS" (DAV Class 8 Secondary
   Mathematics, Brain Teasers / HOTS / Enrichment, all 16 chapters),
   transcribed by vision from the scanned PDF, with verified correct answers.
   Image/figure-dependent questions are EXCLUDED per user's rule.

   Entry shape:
     { id, ch, q,                     // canonical question text
       need: [...],                   // strings that MUST all appear in answer
       any: [...],                    // OR-list: at least one must appear
       opt: 'ii' }                    // for MCQs: correct option label
   Answer checking is done on normalized text (lowercase, commas stripped).
   ═══════════════════════════════════════════════════════════════════════════ */
(function (root) {
    var BANK = [
        /* ── CH 1 · Squares & Square Roots ─────────────────────────────── */
        { id: 'c1.m1', ch: 1, q: 'The difference between the squares of two consecutive numbers is equal to their (i) difference (ii) sum (iii) product (iv) quotient', opt: 'ii', any: ['sum'] },
        { id: 'c1.m2', ch: 1, q: 'What will be the digit in the thousands place of (1111)^2?', any: ['4'] },
        { id: 'c1.m3', ch: 1, q: 'Perfect squares cannot have 2, 3, _ and _ in their ones place. Options (i) 1,7 (ii) 5,6 (iii) 7,8 (iv) 7,9', opt: 'iii', any: ['7, 8', '7 and 8', '7,8'] },
        { id: 'c1.m4', ch: 1, q: 'The smallest number by which 72 must be divided to make it a perfect square is (i) 4 (ii) 5 (iii) 3 (iv) 2', opt: 'iv', any: ['2'] },
        { id: 'c1.m5', ch: 1, q: 'The square root of 3.052009 has how many decimal places? (i) 3 (ii) 4 (iii) 5 (iv) 1', opt: 'i', any: ['3'] },
        { id: 'c1.b1', ch: 1, q: 'How many non-square numbers are there between 13^2 and 14^2?', any: ['26'] },
        { id: 'c1.b2', ch: 1, q: 'Write the first four triangular numbers.', any: ['1, 3, 6, 10', '1,3,6,10'] },
        { id: 'c1.b3', ch: 1, q: 'Is 5, 7, 9 a Pythagorean triplet? Why? Justify.', any: ['no'] },
        { id: 'c1.b4', ch: 1, q: 'Find the square root of 9 by repeated subtraction method.', any: ['3'] },
        { id: 'c1.b5', ch: 1, q: 'Find the measure of the side of a square handkerchief of area 324 cm^2.', any: ['18'] },
        { id: 'c1.q2', ch: 1, q: 'Find the square root of 10 correct to four places of decimal.', any: ['3.1623'] },
        { id: 'c1.q3', ch: 1, q: 'Find the values of sqrt(3.1428) and sqrt(0.31428) correct to three decimal places.', need: ['1.773', '0.561'] },
        { id: 'c1.q4i', ch: 1, q: 'Simplify: sqrt(0.0441) / sqrt(0.000441)', any: ['10'] },
        { id: 'c1.q4ii', ch: 1, q: 'Simplify: sqrt(49) + sqrt(0.49) + sqrt(0.0049)', any: ['7.77'] },
        { id: 'c1.q5', ch: 1, q: 'The area of a square field is 101 1/400 m^2. Find the length of one side of the field.', any: ['10.05'] },
        { id: 'c1.q6', ch: 1, q: 'What is that number which when multiplied by itself gives 227.798649?', any: ['15.093'] },
        { id: 'c1.q7', ch: 1, q: 'In a lecture hall, 8649 students are sitting in such a manner that there are as many students in a row as there are rows in the lecture hall. How many students are there in each row?', any: ['93'] },
        { id: 'c1.q8', ch: 1, q: 'A General wishing to draw up his 64019 men in the form of a square found that he had 10 men extra. Find the number of men in the front row.', any: ['253'] },
        { id: 'c1.h1', ch: 1, q: 'The cost of levelling a square lawn at Rs 15 per square metre is Rs 20535. Find the cost of fencing the lawn at Rs 22 per metre.', any: ['3256'] },
        { id: 'c1.h2i', ch: 1, q: 'If sqrt(2) = 1.414, sqrt(5) = 2.236 and sqrt(3) = 1.732, find the value of sqrt(72) + sqrt(48).', any: ['15.412'] },
        { id: 'c1.h2ii', ch: 1, q: 'If sqrt(2) = 1.414, sqrt(5) = 2.236 and sqrt(3) = 1.732, find the value of sqrt(125/64).', any: ['1.3975'] },
        { id: 'c1.e1', ch: 1, q: 'The product of two numbers is 1296. If one number is 16 times the other, find the numbers.', need: ['9', '144'] },
        { id: 'c1.e2', ch: 1, q: 'Find the value of sqrt(50625) and hence the value of sqrt(506.25) + sqrt(5.0625).', need: ['225', '24.75'] },
        { id: 'c1.e3', ch: 1, q: 'Write a Pythagorean triplet if the smallest number is 14.', need: ['14', '48', '50'] },

        /* ── CH 2 · Cubes & Cube Roots ─────────────────────────────────── */
        { id: 'c2.v1', ch: 2, q: 'Provisions were packed in six cubical cartons each of side measuring 65 cm. Find the volume of cartons packed.', any: ['1647750'] },
        { id: 'c2.v2', ch: 2, q: 'The number of students getting prizes in three categories are in the ratio 1:2:3. If product of ratios is 162, find the number of students getting prizes for each value.', need: ['3', '6', '9'] },
        { id: 'c2.m1', ch: 2, q: 'Cube of 0.1 is equal to (i) 1.11 (ii) 0.001 (iii) 0.101 (iv) 0.01', opt: 'ii', any: ['0.001'] },
        { id: 'c2.m2', ch: 2, q: 'The smallest number by which 1944 should be multiplied so that it becomes a perfect cube is (i) 3 (ii) 2 (iii) 5 (iv) 4', opt: 'i', any: ['3'] },
        { id: 'c2.m3', ch: 2, q: 'Value of cube root of 1000000 is (i) 10 (ii) 1000 (iii) 100 (iv) none of these', opt: 'iii', any: ['100'] },
        { id: 'c2.m4', ch: 2, q: 'cube root of 0.027 minus cube root of 0.008 is equal to (i) 1 (ii) 0.1 (iii) 0.11 (iv) 0.09', opt: 'ii', any: ['0.1'] },
        { id: 'c2.m5', ch: 2, q: 'Cube of (-1/3) is equal to (i) 1/27 (ii) -1/9 (iii) -1/27 (iv) 1/9', opt: 'iii', any: ['-1/27'] },
        { id: 'c2.b1', ch: 2, q: 'Find the number whose cube is 1728.', any: ['12'] },
        { id: 'c2.b2', ch: 2, q: 'Find the value of the cube root of 216 x (-125).', any: ['-30'] },
        { id: 'c2.b3', ch: 2, q: 'Find the cube root of 0.000001', any: ['0.01'] },
        { id: 'c2.b4', ch: 2, q: 'What is the smallest number by which 1715 should be divided so that the quotient is a perfect cube?', any: ['5'] },
        { id: 'c2.b5', ch: 2, q: 'Evaluate: cube root of (0.512 / 0.343)', any: ['8/7', '1.142857'] },
        { id: 'c2.q4', ch: 2, q: 'Find the cubes of: (i) 0.6 (ii) -3.1 (iii) -0.01', need: ['0.216', '-29.791', '-0.000001'] },
        { id: 'c2.q5i', ch: 2, q: 'Find the value of the cube root of 0.008', any: ['0.2'] },
        { id: 'c2.q5ii', ch: 2, q: 'Find the value of the cube root of (-64/1331)', any: ['-4/11'] },
        { id: 'c2.q5iii', ch: 2, q: 'Find the value of the cube root of (27 x 2744)', any: ['42'] },
        { id: 'c2.q6', ch: 2, q: 'Find the smallest number which when multiplied with 3600 will make the product a perfect cube. Further, find the cube root of the product.', need: ['60'] },
        { id: 'c2.q7', ch: 2, q: 'Evaluate: cube root of (0.027/0.008) divided by sqrt(0.09/0.04) minus 1', any: ['0'] },
        { id: 'c2.q8', ch: 2, q: 'Find the cube root of the following numbers: (i) 6859 (ii) 12167 (iii) 32768', need: ['19', '23', '32'] },
        { id: 'c2.h1', ch: 2, q: 'Evaluate: cube root of ( 288 x cube root of ( 72 x cube root of 27 ) )', any: ['12'] },
        { id: 'c2.h2', ch: 2, q: 'Three numbers are in the ratio 2:3:4. The sum of their cubes is 33957. Find the numbers.', need: ['14', '21', '28'] },
        { id: 'c2.e1', ch: 2, q: 'Find the cube root of 4741632 by estimation.', any: ['168'] },
        { id: 'c2.e2', ch: 2, q: 'Find the volume of a cube whose surface area is 150 m^2.', any: ['125'] },

        /* ── CH 3 · Exponents & Radicals ───────────────────────────────── */
        { id: 'c3.v1', ch: 3, q: 'Nine sections of Class VIII were each provided a sheet measuring 75 cm x 40 cm for making a poster. Find the total area of sheet provided and express it in exponential form.', any: ['27000'] },
        { id: 'c3.m1', ch: 3, q: 'Value of { (625)^(-1/2) }^2 is (i) 1/625 (ii) -25 (iii) -625 (iv) 25', opt: 'i', any: ['1/625'] },
        { id: 'c3.m2', ch: 3, q: 'If 5^x = 1, value of x is (i) 5 (ii) 1/25 (iii) 0 (iv) 1/5', opt: 'iii', any: ['0'] },
        { id: 'c3.m3', ch: 3, q: 'Value of ( 27^(1/3) + 64^(1/3) )^2 is (i) 7^(1/3) (ii) 49 (iii) 7^(1/2) (iv) 1/7', opt: 'ii', any: ['49'] },
        { id: 'c3.m4', ch: 3, q: 'For any two non-zero rational numbers a and b, a^4 divided by b^4 is equal to (i) (a/b)^1 (ii) (a/b)^0 (iii) (a/b)^4 (iv) (a/b)^8', opt: 'iii', any: ['(a', 'a ÷ b)4', '(a ÷ b)^4'] },
        { id: 'c3.m5', ch: 3, q: '4.25 x 10^-7 is equal to (i) 0.425000000 (ii) 4250000 (iii) 0.000000425 (iv) 0.00000425', opt: 'iii', any: ['0.000000425'] },
        { id: 'c3.b2', ch: 3, q: 'Find the value of (81)^(-3/4)', any: ['1/27'] },
        { id: 'c3.b3', ch: 3, q: 'Simplify 5 x 16^(3/4)', any: ['40'] },
        { id: 'c3.b4', ch: 3, q: 'Evaluate (0.000064)^(5/6)', any: ['0.00032'] },
        { id: 'c3.b5', ch: 3, q: 'Solve for x if 3^(x-1) = 1/27', any: ['-2'] },
        { id: 'c3.q2', ch: 3, q: 'Simplify: (64)^(-1/6) x (216)^(-1/3) x (81)^(1/4) divided by ( (512)^(-1/3) x (16)^(1/4) x (9)^(-1/2) )', any: ['3'] },
        { id: 'c3.q4i', ch: 3, q: 'Evaluate: 3 x (16)^(3/4)', any: ['24'] },
        { id: 'c3.q4ii', ch: 3, q: 'Evaluate: 2 x (27)^(-2/3)', any: ['2/9'] },
        { id: 'c3.q4iii', ch: 3, q: 'Evaluate: 2 x 9^(3/2) x 9^(-1/2)', any: ['18'] },
        { id: 'c3.q5', ch: 3, q: 'Find the value of [ (5)^2 + (12)^2 ]^(1/2)', any: ['13'] },
        { id: 'c3.q6i', ch: 3, q: 'Find the value of x if 2^x + 2^x + 2^x = 192', any: ['6'] },
        { id: 'c3.q6ii', ch: 3, q: 'Find the value of x if 8^255 = (32)^x', any: ['153'] },
        { id: 'c3.q6iii', ch: 3, q: 'Find the value of x if 2^(2x+2) = 4^(2x-1)', any: ['2'] },
        { id: 'c3.q7', ch: 3, q: 'If 4^x - 4^(x-1) = 24, then find the value of x.', any: ['5/2', '2.5'] },
        { id: 'c3.h1', ch: 3, q: 'Evaluate: (6^-1 - 8^-1)^-1 + (2^-1 - 3^-1)^-1', any: ['30'] },
        { id: 'c3.h2', ch: 3, q: 'If 3^(x-1) = 9 and 4^(y+2) = 64, find the value of y/x - x/y.', any: ['-8/3'] },

        /* ── CH 4 · Direct & Inverse Variation ─────────────────────────── */
        { id: 'c4.m1', ch: 4, q: 'Both x and y are in direct proportion. Then 1/x and 1/y are (i) in direct proportion (ii) in inverse proportion (iii) neither (iv) sometimes direct sometimes inverse', opt: 'ii', any: ['inverse'] },
        { id: 'c4.m2', ch: 4, q: 'If two quantities x and y vary inversely with each other, then (i) x/y remains constant (ii) (x-y) remains constant (iii) (x+y) remains constant (iv) (xy) remains constant', opt: 'iv', any: ['xy'] },
        { id: 'c4.m3', ch: 4, q: 'Both p and q vary directly with each other. When p is 10 and q is 15, which of the following is NOT a possible pair of corresponding values of p and q? (i) 15 and 20 (ii) 20 and 30 (iii) 2 and 3 (iv) 5 and 7.5', opt: 'i', any: ['15 and 20'] },
        { id: 'c4.m4', ch: 4, q: 'If x and y vary directly with each other and x = 24, what is y when the constant of variation is 3? (i) 21 (ii) 1/8 (iii) 8 (iv) 27', opt: 'iii', any: ['8'] },
        { id: 'c4.m5', ch: 4, q: 'Which of the quantities vary inversely with each other? (i) distance travelled and cab fare (ii) area of a land and its cost (iii) number of workers and amount of work done (iv) number of workers and time taken to finish a job', opt: 'iv', any: ['time taken to finish'] },
        { id: 'c4.b1', ch: 4, q: 'l varies directly as m and l is equal to 5 when m = 2/3. Find l when m = 16/3.', any: ['40'] },
        { id: 'c4.b2', ch: 4, q: 'A bowler throws a cricket ball at a speed of 36 km/hr. How long does this ball take to travel a distance of 20 metres to reach the batsman?', any: ['2 s', '2 sec', '2 second'] },
        { id: 'c4.b3', ch: 4, q: 'Sweets from a packet were distributed among 50 children and each of them received four sweets. If it is distributed among 40 children, how many sweets will each child get?', any: ['5'] },
        { id: 'c4.b4', ch: 4, q: 'If y is directly proportional to 1/x and x = 2 when y = 20, what is the value of x when y = 1.25?', any: ['32'] },
        { id: 'c4.b5', ch: 4, q: 'If l is inversely proportional to sqrt(m) and l = 6 when m = 4, what is the value of m when l = 4?', any: ['9'] },
        { id: 'c4.q2i', ch: 4, q: 'Determine whether x and y vary directly, inversely or neither, given: x = 12, 3, 27, 6, 2 and y = 9, 36, 4, 18, 54', any: ['inverse'] },
        { id: 'c4.q2ii', ch: 4, q: 'Determine whether x and y vary directly, inversely or neither, given: x = 4, 20, 30, 40, 60, 80 and y = 2, 8, 10, 15, 20, 25', any: ['neither'] },
        { id: 'c4.q2iii', ch: 4, q: 'Determine whether x and y vary directly, inversely or neither, given: x = 2, 9, 7, 4, 3 and y = 10, 45, 35, 20, 15', any: ['direct'] },
        { id: 'c4.q3', ch: 4, q: 'If x and y vary inversely and x = 25 when y = 3, find y when x = 15.', any: ['5'] },
        { id: 'c4.q4', ch: 4, q: 'If x and y vary inversely and y = 45, find x when the constant of variation is 9.', any: ['0.2', '1/5'] },
        { id: 'c4.q5', ch: 4, q: 'Oranges cost Rs 54 for three dozens in the super market. What is the cost of eight oranges?', any: ['12'] },
        { id: 'c4.q6', ch: 4, q: 'A car travels 60 km in 1 hr 30 min. How long will it take to cover a distance of 100 km at the same speed?', any: ['2.5', '2 hr 30', '2 hours 30', '2 h 30'] },
        { id: 'c4.q7', ch: 4, q: 'The extension of an elastic spring varies directly with the weight suspended from it. If a weight of 75 kg produces an extension of 1.4 cm, calculate the weight that would produce an extension of 9.8 cm.', any: ['525'] },
        { id: 'c4.q8', ch: 4, q: 'In 25 days, the earth picks up 6 x 10^8 pounds of dust from the atmosphere. How much dust will it pick up in 15 days?', any: ['3.6'] },
        { id: 'c4.h1', ch: 4, q: 'While driving his car at a speed of 50 km/hr, Ramit covers a distance from home to his office in 1 hour 30 minutes. One day he was 15 minutes late from his home. In order to reach office at time, what should be the speed of the car? Also find the total distance covered by Ramit daily.', need: ['60', '75'] },

        /* ── CH 5 · Profit, Loss & Discount ────────────────────────────── */
        { id: 'c5.m1', ch: 5, q: 'If the selling price of an article is twice the cost price, the profit per cent is (i) 50% (ii) 100% (iii) 150% (iv) 200%', opt: 'ii', any: ['100'] },
        { id: 'c5.m2', ch: 5, q: 'A jeans is marked for Rs 2590 but is sold for Rs 2331, then discount per cent is (i) 20% (ii) 15% (iii) 10% (iv) 5%', opt: 'iii', any: ['10'] },
        { id: 'c5.m3', ch: 5, q: 'If selling price of five pens is equal to the cost price of four pens, then the gain or loss per cent is (i) 20% gain (ii) 20% loss (iii) 25% loss (iv) 25% gain', opt: 'ii', any: ['20% loss', '20 % loss', 'loss of 20'] },
        { id: 'c5.m4', ch: 5, q: 'Selling price of shoes is Rs 420 including 5% GST. The original price of the shoes is (i) Rs 442 (ii) Rs 400 (iii) Rs 401.50 (iv) Rs 420', opt: 'ii', any: ['400'] },
        { id: 'c5.m5', ch: 5, q: 'Discount is always calculated on (i) cost price (ii) marked price (iii) selling price (iv) GST', opt: 'ii', any: ['marked price'] },
        { id: 'c5.b1', ch: 5, q: 'After giving a discount of 8% on the marked price, an article was sold for Rs 414. Find the marked price of the article.', any: ['450'] },
        { id: 'c5.b2', ch: 5, q: 'A fan is sold for Rs 650. The gain is one-fourth of the cost price of the fan. Find the gain per cent.', any: ['25'] },
        { id: 'c5.b3', ch: 5, q: 'A shopkeeper buys pencils at 10 for Rs 10 and sells them at 8 for Rs 10. Find the profit per cent.', any: ['25'] },
        { id: 'c5.b4', ch: 5, q: 'Find the rate of GST if an article marked at Rs 5000 is sold for Rs 5900.', any: ['18'] },
        { id: 'c5.b5', ch: 5, q: 'A person pays Rs 2800 for a cooler marked at Rs 3500. Find the discount per cent offered.', any: ['20'] },
        { id: 'c5.q2', ch: 5, q: 'Rajan purchased a purse at 25% discount on its marked price but sold it at the marked price. Find the gain per cent of Rajan on this transaction.', any: ['33.33', '33 1/3', '33.3'] },
        { id: 'c5.q3', ch: 5, q: 'Jasleen marks her goods at 30% above the cost price and allows a discount of 25% on the marked price. Find her gain or loss per cent.', any: ['2.5', 'loss'] },
        { id: 'c5.q4', ch: 5, q: 'How much per cent above the cost price should a shopkeeper mark his goods so that after allowing a discount of 20% on the marked price, he gains 12%?', any: ['40'] },
        { id: 'c5.q5', ch: 5, q: 'Rohit marks his goods at 40% above the cost price but allows a discount of 5% for cash payment. What actual profit does he make if he receives Rs 1064 after allowing the discount?', any: ['264'] },
        { id: 'c5.q6', ch: 5, q: 'Mrs Kumar bought a saree for Rs 12500, clothes for the kids for Rs 9280 and shirts for Mr Kumar for Rs 10445. If the GST charged on the purchases is 12%, then what is the total amount that Mr Kumar has paid?', any: ['36092'] },
        { id: 'c5.h1', ch: 5, q: 'The marked price of an article is Rs 3500 and rate of GST is 12%. A shopkeeper allows a discount of 20% and still makes a profit of 10%. Find the original cost price of the article and the selling price including GST.', need: ['3136'] },

        /* ── CH 6 · Compound Interest ──────────────────────────────────── */
        { id: 'c6.m1', ch: 6, q: 'For a given rate of interest and time, what is more profitable to the depositor? (i) compound interest (ii) simple interest (iii) both equally (iv) cannot be determined', opt: 'i', any: ['compound'] },
        { id: 'c6.m2', ch: 6, q: 'A sum of Rs 10000 at 8% per annum for six months compounded quarterly amounts to (i) Rs 400 (ii) Rs 404 (iii) Rs 408 (iv) Rs 10404', opt: 'iv', any: ['10404'] },
        { id: 'c6.m3', ch: 6, q: 'In A = P(1 + R/100)^n, A stands for (i) time period (ii) principal (iii) principal + interest (iv) interest', opt: 'iii', any: ['principal + interest', 'amount'] },
        { id: 'c6.m4', ch: 6, q: 'If the number of conversion periods is greater than or equal to 2, then compound interest is (i) less than simple interest (ii) greater than simple interest (iii) less than or equal to simple interest (iv) greater than or equal to simple interest', opt: 'ii', any: ['greater than simple'] },
        { id: 'c6.m5', ch: 6, q: 'Reema wants to do a one-year deposit. She should opt for (i) simple interest of 10% (ii) compound interest of 10% compounded quarterly (iii) compound interest of 10% compounded annually (iv) compound interest of 10% compounded half-yearly', opt: 'ii', any: ['quarterly'] },
        { id: 'c6.b1', ch: 6, q: 'Find the compound interest on Rs 1000 at 10% per annum for two years.', any: ['210'] },
        { id: 'c6.b2', ch: 6, q: 'If Rs 6000 is deposited for two years at 4% per annum compounded quarterly, then find the time period and rate to compute compound interest.', need: ['8', '1'] },
        { id: 'c6.b3', ch: 6, q: 'The value of a machine worth Rs 500000 depreciates at the rate of 10% every year. In how many years will its value be Rs 364500?', any: ['3'] },
        { id: 'c6.b4', ch: 6, q: 'Find the difference between the compound interest and simple interest on Rs 5000 for two years at 5% per annum.', any: ['12.5'] },
        { id: 'c6.b5', ch: 6, q: 'If Rs 20000 is deposited for three years at 5% compounded annually, then what will be the principal for the second year?', any: ['21000'] },
        { id: 'c6.q2', ch: 6, q: 'Preeti invested Rs 50000 at 8% per annum for three years, interest compounded annually. Calculate (a) the amount standing to her credit at the end of the second year (b) the interest for the third year.', need: ['58320', '4665.6'] },
        { id: 'c6.q3', ch: 6, q: 'A man had Rs 75000. He invested Rs 35000 in a company which pays him 9% interest per annum and the rest in another company which pays him 9.5% interest per annum. Find the total compound interest received by him after two years.', any: ['14544.5'] },
        { id: 'c6.q4', ch: 6, q: 'A certain sum of money at compound interest becomes Rs 7396 in two years and Rs 7950.70 in three years. Find the rate of interest.', any: ['7.5'] },
        { id: 'c6.q5', ch: 6, q: 'Pooja started a business by investing Rs 200000. During the first three successive years she earned a profit of 5%, 8% and 12% per annum respectively, each added to the capital. Calculate her total profit after three years.', any: ['54016'] },
        { id: 'c6.q6', ch: 6, q: 'Mahesh borrowed a certain sum for two years at simple interest and lent it at the same rate for two years at compound interest. At the end of two years he received Rs 410 as compound interest but paid Rs 400 as simple interest. Find the sum and rate of interest.', need: ['4000', '5'] },
        { id: 'c6.q7', ch: 6, q: 'A man invested Rs 1000 for three years at 11% simple interest per annum and Rs 1000 at 10% compound interest per annum compounded annually for three years. Find which investment is better.', any: ['compound'] },
        { id: 'c6.q8', ch: 6, q: 'M/s Heera Associates let out Rs 400000 for one year at 16% per annum compounded annually. How much more could they earn if the interest is compounded half-yearly?', any: ['2560'] },
        { id: 'c6.q9', ch: 6, q: 'Sirish borrowed a sum of Rs 163840 at 12.5% per annum compounded annually. On the same day he lent out the same amount to Sahej at the same rate of interest but compounded half-yearly. Find his gain after two years.', any: ['1442.5'] },
        { id: 'c6.q10', ch: 6, q: 'The annual rate of growth in population of a certain city is 8%. If its present population is 196830, what was the population three years ago?', any: ['156250'] },
        { id: 'c6.e1', ch: 6, q: 'A builder employed 4000 workers on a residential project. At the end of the first year 10% workers were removed, at the end of the second year 5% of those working at that time were retrenched, and at the end of the third year the number of workers was increased by 15%. How many workers were working during the fourth year?', any: ['3933'] },

        /* ── CH 7 · Algebraic Identities ───────────────────────────────── */
        { id: 'c7.m1', ch: 7, q: 'The factors of (1 - 6z + 9z^2) are (i) (1+3z)(1-3z) (ii) (z+3)^2 (iii) (3z-1)^2 (iv) (z-3)^2', opt: 'iii', any: ['(3z - 1)', '(3z-1)'] },
        { id: 'c7.m2', ch: 7, q: 'Which of the following is an algebraic identity? (i) (a-b)^2 = a^2+2ab-b^2 (ii) (a-b)^2 = a^2-2ab-b^2 (iii) (a-b)^2 = a^2-b^2 (iv) (a-b)^2 = a^2-2ab+b^2', opt: 'iv', any: ['a² - 2ab + b²', 'a^2 - 2ab + b^2', 'a2 - 2ab + b2'] },
        { id: 'c7.m3', ch: 7, q: 'Factorised form of y^2 + 3y + y + 3 is (i) (y+2)(y+1) (ii) (y+3)^2 (iii) (y+1)(y+3) (iv) y^2+3^2', opt: 'iii', any: ['(y + 1)(y + 3)', '(y+1)(y+3)'] },
        { id: 'c7.m4', ch: 7, q: 'Factorised form of p^2 - 17p - 38 is (i) (p-19)(p+2) (ii) (p-19)(p-2) (iii) (p+19)(p+2) (iv) (p+19)(p-2)', opt: 'i', any: ['(p - 19)(p + 2)', '(p-19)(p+2)'] },
        { id: 'c7.m5', ch: 7, q: 'A side of the square with area (4x^2 + 12x + 9) square units is (i) (4x+3) units (ii) (4x+9) units (iii) (2x+3) units (iv) (x+3) units', opt: 'iii', any: ['2x + 3', '2x+3'] },
        { id: 'c7.b1', ch: 7, q: 'Find the product using suitable identity: (a+3)(a-3)(a^2+9)', any: ['a⁴ - 81', 'a^4 - 81'] },
        { id: 'c7.b2', ch: 7, q: 'If x^2 + 1/x^2 = 6, find the value of x^4 + 1/x^4.', any: ['34'] },
        { id: 'c7.b3', ch: 7, q: 'Find the value of k if: x y^2 k = (4xy + 3y)^2 - (4xy - 3y)^2', any: ['48'] },
        { id: 'c7.b4', ch: 7, q: 'If a^2 + b^2 = 9 and ab = 4, find the value of 3(a+b)^2 - 2(a-b)^2.', any: ['49'] },
        { id: 'c7.b5', ch: 7, q: 'If a + b + c = 12 and a^2 + b^2 + c^2 = 64, find the value of ab + bc + ac.', any: ['40'] },
        { id: 'c7.q2i', ch: 7, q: 'Find the product using a suitable identity: (7x - 9y)(7x - 9y)', any: ['49x² - 126xy + 81y²', '49x^2 - 126xy + 81y^2'] },
        { id: 'c7.q2ii', ch: 7, q: 'Find the product using a suitable identity: (6ax + 5by)(6ax - 5by)', any: ['36a²x² - 25b²y²', '36a^2x^2 - 25b^2y^2'] },
        { id: 'c7.q2v', ch: 7, q: 'Find the product using a suitable identity: (x + 2y)(x - 2y)(x^2 + 4y^2)', any: ['x⁴ - 16y⁴', 'x^4 - 16y^4'] },
        { id: 'c7.q3i', ch: 7, q: 'Express 4x^2 + 12xy + 9y^2 as a square of a binomial and evaluate for x = -2, y = 2.', any: ['4'] },
        { id: 'c7.q3ii', ch: 7, q: 'Express (4/25)m^2 - mn + (25/16)n^2 as a square of a binomial and evaluate for m = 5, n = 8.', any: ['64'] },
        { id: 'c7.q4i', ch: 7, q: 'Simplify: (a+b)^2 + (a-b)^2', any: ['2(a² + b²)', '2(a^2 + b^2)', '2a² + 2b²', '2a^2 + 2b^2'] },
        { id: 'c7.q4ii', ch: 7, q: 'Simplify: (3x + 7y)^2 - (3x - 7y)^2', any: ['84xy'] },
        { id: 'c7.q5i', ch: 7, q: 'Evaluate by using a suitable identity: (399)^2', any: ['159201'] },
        { id: 'c7.q5ii', ch: 7, q: 'Evaluate by using a suitable identity: (62)^2', any: ['3844'] },
        { id: 'c7.q5iii', ch: 7, q: 'Evaluate by using a suitable identity: 103 x 97', any: ['9991'] },
        { id: 'c7.q5iv', ch: 7, q: 'Evaluate by using a suitable identity: (10.1)^2', any: ['102.01'] },
        { id: 'c7.q5v', ch: 7, q: 'Evaluate by using a suitable identity: (85)^2 - (75)^2', any: ['1600'] },
        { id: 'c7.q5vi', ch: 7, q: 'Evaluate by using a suitable identity: 291 x 309', any: ['89919'] },
        { id: 'c7.q6i', ch: 7, q: 'Evaluate x if 36x = 78^2 - 42^2', any: ['120'] },
        { id: 'c7.q6ii', ch: 7, q: 'Evaluate x if 6.2x = 8.1 x 8.1 - 1.9 x 1.9', any: ['10'] },
        { id: 'c7.q7i', ch: 7, q: 'Factorise: z^2 - 4z - 77', any: ['(z - 11)(z + 7)', '(z-11)(z+7)'] },
        { id: 'c7.q7ii', ch: 7, q: 'Factorise: x^2 + 25x + 144', any: ['(x + 9)(x + 16)', '(x+9)(x+16)'] },
        { id: 'c7.q7iii', ch: 7, q: 'Factorise: x^2 + 5x - 104', any: ['(x + 13)(x - 8)', '(x+13)(x-8)'] },
        { id: 'c7.q7iv', ch: 7, q: 'Factorise: 49x^2 - 64', any: ['(7x - 8)(7x + 8)', '(7x-8)(7x+8)'] },
        { id: 'c7.q8', ch: 7, q: 'If x + 1/x = 8, find the value of x^2 + 1/x^2.', any: ['62'] },
        { id: 'c7.q9', ch: 7, q: 'If a - 1/a = 5, find the value of a^2 + 1/a^2.', any: ['27'] },
        { id: 'c7.q10', ch: 7, q: 'If a^2 + 1/a^2 = 23, find the value of (a + 1/a).', any: ['5'] },
        { id: 'c7.q11', ch: 7, q: 'If x^2 + 1/x^2 = 51, find the value of (x - 1/x).', any: ['7'] },
        { id: 'c7.q12', ch: 7, q: 'Simplify: (2.3 x 2.3 - 0.3 x 0.3) / (2.3 x 2.3 - 2 x 2.3 x 0.3 + 0.3 x 0.3)', any: ['1.3'] },
        { id: 'c7.q13', ch: 7, q: 'If 3x + 4y = 10 and xy = -1, find the value of 9x^2 + 16y^2.', any: ['124'] },
        { id: 'c7.q14', ch: 7, q: 'If 5x - 2y = 7 and xy = 2, find the value of (5x + 2y)^2.', any: ['129'] },
        { id: 'c7.q15', ch: 7, q: 'If a + 1/a = 17/4, find the value of (a - 1/a).', any: ['15/4', '3.75'] },
        { id: 'c7.h1', ch: 7, q: 'The sum of (x + 3) observations is (x^4 - 81). Find the mean of the observations.', any: ['x³ - 3x² + 9x - 27', 'x^3 - 3x^2 + 9x - 27'] },
        { id: 'c7.h2', ch: 7, q: 'The area of a circle is given by the expression (pi x^2 + 10 pi x + 25 pi). Find the radius of the circle.', any: ['x + 5', 'x+5'] },

        /* ── CH 8 · Polynomials ────────────────────────────────────────── */
        { id: 'c8.v1', ch: 8, q: 'Mr Lalit donated Rs (x^2 + 12x + 35) for the education of (x + 7) children. Find the amount received by each child if each child got the equal amount.', any: ['x + 5', 'x+5'] },
        { id: 'c8.v2', ch: 8, q: 'Abhay jogs a distance of (2t^4 + 3t^3 - 2t^2 - 9t - 12) km at the speed of (t^2 - 3) km/hr. Find the time taken by him.', any: ['2t² + 3t + 4', '2t^2 + 3t + 4'] },
        { id: 'c8.m1', ch: 8, q: 'Value of p for which (x^2 + 3x + p) is divisible by (x - 2) is (i) 10 (ii) -10 (iii) 5 (iv) -5', opt: 'ii', any: ['-10'] },
        { id: 'c8.m2', ch: 8, q: 'Quotient obtained when (x^2 + 7x - 4) is divided by (x + 7) is (i) x (ii) x-4 (iii) x+4 (iv) x+2', opt: 'i', any: ['x'] },
        { id: 'c8.m3', ch: 8, q: 'Polynomial which when divided by (-x^2 + x - 1) gives a quotient (x - 2) and remainder 3 is (i) x^3-3x^2+3x-5 (ii) -x^3+3x^2-3x+5 (iii) -x^3+3x^2-3x-5 (iv) x^3-3x^2-3x+5', opt: 'ii', any: ['-x³ + 3x² - 3x + 5', '-x^3 + 3x^2 - 3x + 5'] },
        { id: 'c8.m4', ch: 8, q: 'What should be added to the polynomial x^2 - 5x + 4 so that (x - 3) is a factor of the resulting polynomial? (i) 1 (ii) 2 (iii) 4 (iv) 5', opt: 'ii', any: ['2'] },
        { id: 'c8.m5', ch: 8, q: 'What should be subtracted from the polynomial x^2 - 16x + 30 so that (x - 15) is a factor of the resulting polynomial? (i) 30 (ii) 14 (iii) 15 (iv) 16', opt: 'iii', any: ['15'] },
        { id: 'c8.b2', ch: 8, q: 'If (x - 3) is a factor of the polynomial (2x^2 + x + k), find k.', any: ['-21'] },
        { id: 'c8.b3', ch: 8, q: 'Can (x - 1) be the remainder on division of a polynomial p(x) by (x + 3)? Justify your answer.', any: ['no'] },
        { id: 'c8.b4', ch: 8, q: 'Find the remainder when (x^3 + x - 4x^2 + 6) is divided by (x + 2). What do you conclude whether (x + 2) is a factor or not?', any: ['-20'] },
        { id: 'c8.b5', ch: 8, q: 'If (8y + 8y^2 + 7) is divided by (1 - y), then find the remainder.', any: ['23'] },
        { id: 'c8.q2i', ch: 8, q: 'Divide -39x^4 by sqrt(13) x^2', any: ['-3 sqrt(13) x²', '-3√13 x^2', '-3√13x²'] },
        { id: 'c8.q2ii', ch: 8, q: 'Divide sqrt(125) y^2 by 5y^2', any: ['sqrt(5)', '√5'] },
        { id: 'c8.q2iv', ch: 8, q: 'Divide 14z^6 by (14/3) z^3', any: ['3z³', '3z^3'] },
        { id: 'c8.q2vii', ch: 8, q: 'Divide 18a^3 - 12a^2 + 9a by 3a', any: ['6a² - 4a + 3', '6a^2 - 4a + 3'] },
        { id: 'c8.q3i', ch: 8, q: 'Divide and write the quotient and remainder: 4x^2 + 7x - 11 by 2x - 4', need: ['15/2', '19'] },
        { id: 'c8.q3iii', ch: 8, q: 'Divide and write the quotient and remainder: y^3 + 5y^2 + 12y + 9 by y + 2', need: ['y² + 3y + 6', 'y^2 + 3y + 6', '-3'] },
        { id: 'c8.h1', ch: 8, q: 'The sum of the remainders obtained when (x^3 + (k+8)x + k) is divided by (x - 2) and when it is divided by (x + 1) is zero. Find the value of k.', any: ['-5'] },

        /* ── CH 9 · Linear Equations in One Variable ───────────────────── */
        { id: 'c9.v1', ch: 9, q: 'If a scooterist drives at 24 km/hr he reaches his work place 5 minutes late, but at 30 km/hr he reaches 4 minutes early. Find the distance of his work place from his home.', any: ['18'] },
        { id: 'c9.v2', ch: 9, q: 'A school wants to give 15 prizes for discipline, politeness and punctuality. Politeness prizes are five-sixth of discipline prizes and punctuality prizes are four-fifths of politeness prizes. Find the number of prizes for each value.', need: ['6', '5', '4'] },
        { id: 'c9.m1', ch: 9, q: 'If 5x/3 - 4 = 2x/5, then the numerical value of (2x - 7) is (i) 19/13 (ii) -13/19 (iii) 0 (iv) 13/19', opt: 'ii', any: ['-13/19'] },
        { id: 'c9.m2', ch: 9, q: 'A number 351 is divided into two parts in the ratio 2:7. The product of the numbers is (i) 20294 (ii) 21294 (iii) 25295 (iv) 31294', opt: 'ii', any: ['21294'] },
        { id: 'c9.m3', ch: 9, q: 'Value of x for which (2x-3)/(3x+2) = -2/3 is (i) 5/10 (ii) 5/11 (iii) 11/5 (iv) 5/12', opt: 'iv', any: ['5/12'] },
        { id: 'c9.m4', ch: 9, q: 'Solution of a linear equation in one variable is always (i) a natural number (ii) a whole number (iii) a real number (iv) an integer', opt: 'iii', any: ['real'] },
        { id: 'c9.m5', ch: 9, q: 'The perimeter of a rectangle is numerically equal to its area. If the width of the rectangle is 2 3/4 cm, then its length is (i) 11/3 cm (ii) 22/3 cm (iii) 11 cm (iv) 10 cm', opt: 'ii', any: ['22/3'] },
        { id: 'c9.b1', ch: 9, q: 'Find a number whose fifth part increased by 30 is equal to its fourth part decreased by 30.', any: ['1200'] },
        { id: 'c9.b2', ch: 9, q: 'Raman had 30 flowers. He offered some flowers in a temple and found that the ratio of remaining flowers to flowers in the beginning is 2:5. Find the number of flowers offered by him in the temple.', any: ['18'] },
        { id: 'c9.b3', ch: 9, q: 'The tens and ones digits of a two-digit number are the same. When the number is added to its reverse, the sum is 88. What is the number?', any: ['44'] },
        { id: 'c9.b4', ch: 9, q: 'Solve for x: (x^2 - 9)/(x + 3) = 4/7', any: ['25/7'] },
        { id: 'c9.b5', ch: 9, q: 'Rohan brought a pack of 100 chocolates on his birthday to distribute in his class. After giving two chocolates to each student and his class teacher, he is left with ten chocolates. How many students are there in the class?', any: ['44'] },
        { id: 'c9.q2i', ch: 9, q: 'Solve: (2z + 7)/(3z + 8) = 1/4', any: ['-4'] },
        { id: 'c9.q2ii', ch: 9, q: 'Solve: (3 + 2y)/(2 + 5y) = 7/12', any: ['2'] },
        { id: 'c9.q2iii', ch: 9, q: 'Solve: (2x - 1)/(1 + 5x) = 1/2', any: ['-3'] },
        { id: 'c9.q2iv', ch: 9, q: 'Solve: (5k - 7)/(3k - 9) = -6/7', any: ['103/53'] },
        { id: 'c9.q3i', ch: 9, q: 'Find the positive value of the variable: (1 - x^2)/(1 + x^2) = -4/5', any: ['3'] },
        { id: 'c9.q3ii', ch: 9, q: 'Find the positive value of the variable: (3z^2 + 7)/(4 + z^2) = 2', any: ['1'] },
        { id: 'c9.q4', ch: 9, q: 'Five years ago a mother was seven times as old as her daughter. Five years hence she will be three times as old as her daughter. Find their present ages.', need: ['40', '10'] },
        { id: 'c9.q5', ch: 9, q: 'The digit at ones place of a 2-digit number is four times the digit at tens place. The number obtained by reversing the digits exceeds the given number by 54. Find the given number.', any: ['28'] },
        { id: 'c9.q6', ch: 9, q: 'The sum of the digits of a 2-digit number is 10. The number obtained by interchanging the digits exceeds the original number by 36. Find the original number.', any: ['37'] },
        { id: 'c9.q7', ch: 9, q: 'The sum of two consecutive multiples of 6 is 66. Find these multiples.', need: ['30', '36'] },
        { id: 'c9.q8', ch: 9, q: 'The numerator of a rational number is 3 less than its denominator. If the numerator is increased by 1 and the denominator is increased by 3, the number becomes 1/2. Find the rational number.', any: ['4/7'] },
        { id: 'c9.q9', ch: 9, q: 'A race-boat covers 60 km downstream in one and a half hour and the same distance upstream in 2 hours. The speed of the race-boat in still water is 35 km/hr. Find the speed of the stream.', any: ['5'] },
        { id: 'c9.q10', ch: 9, q: 'The sides (other than hypotenuse) of a right triangle are in the ratio 3:4. A rectangle is described on its hypotenuse, the hypotenuse being the longer side. The breadth of the rectangle is 4/5 of its length. Find the shortest side of the right triangle if the perimeter of the rectangle is 180 cm.', any: ['30'] },
        { id: 'c9.q11', ch: 9, q: 'Divide 243 into three parts such that half of the first part, one-third of the second part and one-fourth of the third part are all equal.', need: ['54', '81', '108'] },
        { id: 'c9.q12', ch: 9, q: 'A purse has only two-rupee and five-rupee coins. The sum of the coins is 36 and the total value of the coins is Rs 84. Find the number of five-rupee coins.', any: ['4'] },
        { id: 'c9.h1', ch: 9, q: 'A number is 6 more than the average of its half, its one-third and its one-sixth. Find the number.', any: ['9'] },
        { id: 'c9.h2', ch: 9, q: 'Solve for x: (x^2 - 3x - 28)/(x^2 - 49) = 3/17, x not equal to plus or minus 7', any: ['47/14'] },

        /* ── CH 10 · Parallel Lines (text-only subset) ─────────────────── */
        { id: 'c10.m1', ch: 10, q: 'A transversal intersects two lines. Which condition would always make the two lines parallel? (i) vertically opposite angles are equal (ii) interior angles on the same side of the transversal are complementary (iii) alternate interior angles are equal (iv) corresponding angles are supplementary', opt: 'iii', any: ['alternate interior'] },
        { id: 'c10.m3', ch: 10, q: 'Transversal TU intersects PQ and RS at V and W. Angle TVQ = 5x - 22 and angle VWS = 3x + 10 (corresponding angles). For which value of x is PQ parallel to RS? (i) 6 (ii) 16 (iii) 24 (iv) 28', opt: 'ii', any: ['16'] },
        { id: 'c10.m4', ch: 10, q: 'Peach Street and Cherry Street are parallel and Apple Street intersects them. If m angle 1 = (2x + 36) degrees and m angle 2 = (7x - 9) degrees are supplementary, what is m angle 1?', any: ['70'] },

        /* ── CH 11 · Quadrilaterals ────────────────────────────────────── */
        { id: 'c11.m1', ch: 11, q: 'The number of diagonals a pentagon has is (i) 2 (ii) 4 (iii) 5 (iv) 3', opt: 'iii', any: ['5'] },
        { id: 'c11.m2', ch: 11, q: 'A parallelogram having its adjacent sides equal is a (i) trapezium (ii) rhombus (iii) triangle (iv) rectangle', opt: 'ii', any: ['rhombus'] },
        { id: 'c11.m3', ch: 11, q: 'A seven sided polygon is called a (i) pentagon (ii) octagon (iii) hexagon (iv) heptagon', opt: 'iv', any: ['heptagon'] },
        { id: 'c11.m4', ch: 11, q: 'Regular polygons are (i) equiangular only (ii) equilateral only (iii) equiangular and equilateral (iv) none', opt: 'iii', any: ['equiangular and equilateral'] },
        { id: 'c11.m5', ch: 11, q: 'Which of the given polygons have equal diagonals? (i) square (ii) rhombus (iii) parallelogram (iv) trapezium', opt: 'i', any: ['square'] },
        { id: 'c11.b1', ch: 11, q: 'Name two polygons whose diagonals bisect each other at right angles.', need: ['rhombus', 'square'] },
        { id: 'c11.b2', ch: 11, q: 'In a parallelogram ABCD, if angle B = 75 degrees, find the measure of angle C.', any: ['105'] },
        { id: 'c11.c1', ch: 11, q: 'What is the measure of each exterior angle of a regular octagon?', any: ['45'] },
        { id: 'c11.e1', ch: 11, q: 'Find each angle of a regular pentagon.', any: ['108'] },
        { id: 'c11.n1', ch: 11, q: 'How many sides has a regular polygon each angle of which is of measure 156 degrees?', any: ['15'] },
        { id: 'c11.n2', ch: 11, q: 'How many sides has a regular polygon each angle of which is of measure 108 degrees?', any: ['5'] },
        { id: 'c11.h1', ch: 11, q: 'Prove that the interior angle of a regular pentagon is three times the exterior angle of a regular decagon.', need: ['108', '36'] },

        /* ── CH 12 · Construction of Quadrilaterals ────────────────────── */
        { id: 'c12.m1', ch: 12, q: 'The number of parts required to construct a quadrilateral is (i) 5 (ii) 4 (iii) 3 (iv) 2', opt: 'i', any: ['5'] },
        { id: 'c12.m2', ch: 12, q: 'To construct a parallelogram, the minimum number of dimensions needed is (i) 2 (ii) 3 (iii) 4 (iv) 1', opt: 'ii', any: ['3'] },
        { id: 'c12.m3', ch: 12, q: 'The minimum number of dimensions needed to construct a square is (i) 1 (ii) 2 (iii) 3 (iv) 4', opt: 'i', any: ['1'] },
        { id: 'c12.m4', ch: 12, q: 'To construct a rectangle, the minimum number of dimensions needed is (i) 1 (ii) 4 (iii) 3 (iv) 2', opt: 'iv', any: ['2'] },

        /* ── CH 13 · Graphs ────────────────────────────────────────────── */
        { id: 'c13.m1', ch: 13, q: 'The point at which the x-axis and y-axis intersect on the cartesian plane is (i) abscissa (ii) origin (iii) ordinate (iv) none', opt: 'ii', any: ['origin'] },
        { id: 'c13.m2', ch: 13, q: 'If a point lies on the y-axis, its coordinates are (i) (x,0) (ii) (0,0) (iii) (x,y) (iv) (0,y)', opt: 'iv', any: ['(0, y)', '(0,y)'] },
        { id: 'c13.m3', ch: 13, q: 'The distance of a point P(2, 3) from the x-axis is (i) 3 units (ii) 2 units (iii) 5 units (iv) 1 unit', opt: 'i', any: ['3'] },
        { id: 'c13.m4', ch: 13, q: 'The distance of a point from the y-axis is called (i) ordinate (ii) y-coordinate (iii) abscissa (iv) none', opt: 'iii', any: ['abscissa'] },
        { id: 'c13.b1', ch: 13, q: 'Write down the coordinates of the origin.', any: ['(0, 0)', '(0,0)'] },
        { id: 'c13.b2', ch: 13, q: 'What are the coordinates of a point which lies on the x-axis?', any: ['(x, 0)', '(x,0)'] },
        { id: 'c13.b3', ch: 13, q: 'What is the distance of the point C(4, 2) from the y-axis?', any: ['4'] },
        { id: 'c13.b4', ch: 13, q: 'What is the distance between the points P(0, 2) and Q(0, 6)?', any: ['4'] },
        { id: 'c13.b5', ch: 13, q: 'If the vertices O, A, B of a square OABC are (0,0), (2,0) and (2,2), what are the coordinates of the fourth vertex C?', any: ['(0, 2)', '(0,2)'] },
        { id: 'c13.h1', ch: 13, q: 'On a cartesian plane plot A(1,1), B(5,1), C(5,5) and D(1,5) and join them in order. What figure do you get and what are the coordinates of the point of intersection of the diagonals?', need: ['square', '(3, 3)', '(3,3)'] },
        { id: 'c13.e1', ch: 13, q: 'On a cartesian plane draw a rectangle whose two vertices are (2,1) and (6,6). Write the coordinates of the other two vertices.', need: ['(2, 6)', '(2,6)', '(6, 1)', '(6,1)'] },
        { id: 'c13.e2', ch: 13, q: 'A line segment XY parallel to x-axis at a distance of 5 units from x-axis and a line segment PQ parallel to y-axis at a distance of 3 units from y-axis intersect. Write the coordinates of their point of intersection.', any: ['(3, 5)', '(3,5)'] },

        /* ── CH 14 · Mensuration ───────────────────────────────────────── */
        { id: 'c14.v2', ch: 14, q: 'A trapezium shaped cardboard has parallel sides 60 cm and 90 cm and the distance between them is 50 cm. Find the area of the trapezium.', any: ['3750'] },
        { id: 'c14.m1', ch: 14, q: 'The volume of a cube of side 0.01 m in cm^3 is (i) 0.001 (ii) 1 (iii) 0.0001 (iv) 0.000001', opt: 'ii', any: ['1'] },
        { id: 'c14.m2', ch: 14, q: 'If the height of a cylinder is halved, its volume will be (i) 1/2 times (ii) 1/3 times (iii) 2 times (iv) 3 times', opt: 'i', any: ['1/2', 'half'] },
        { id: 'c14.m3', ch: 14, q: 'The area of a trapezium having two parallel sides as 10 cm and 12 cm and height as 4 cm is (i) 42 cm^2 (ii) 44 cm^2 (iii) 46 cm^2 (iv) 48 cm^2', opt: 'ii', any: ['44'] },
        { id: 'c14.m5', ch: 14, q: 'If the length of side of a cube is doubled, then the ratio of volumes of new cube and original cube is (i) 1:2 (ii) 2:1 (iii) 4:1 (iv) 8:1', opt: 'iv', any: ['8:1', '8 : 1'] },
        { id: 'c14.b1', ch: 14, q: 'Find the number of edges of a polyhedron having 20 faces and 12 vertices.', any: ['30'] },
        { id: 'c14.b2', ch: 14, q: 'Find the surface area of a cube whose volume is 729 m^3.', any: ['486'] },
        { id: 'c14.b3', ch: 14, q: 'Volume of a cylinder is 2376 cm^3. If the diameter of its base is 12 cm, then find its height.', any: ['21'] },
        { id: 'c14.b5', ch: 14, q: 'Find the total surface area of a cuboid of length 10 cm, breadth 8 cm and height 6 cm.', any: ['376'] },
        { id: 'c14.q2', ch: 14, q: 'Find the area of a quadrilateral whose diagonal is 6 cm and the altitudes on the diagonal from the other two vertices are 3.8 cm and 7.2 cm.', any: ['33'] },
        { id: 'c14.q3', ch: 14, q: 'A field is in the shape of a trapezium. One of its parallel sides is twice the other and the distance between them is 100 m. If the area of the field is 10500 m^2, find the length of the parallel sides.', need: ['70', '140'] },
        { id: 'c14.q4', ch: 14, q: 'Two parallel sides DC and AB of a trapezium are 12 cm and 36 cm respectively. If the non-parallel sides are each equal to 15 cm, find the area of the trapezium.', any: ['216'] },
        { id: 'c14.q5', ch: 14, q: 'The length, breadth and height of a cuboidal box are 2 m 10 cm, 1 m and 80 cm respectively. Find the area of canvas required to cover this box.', any: ['91600'] },
        { id: 'c14.q7', ch: 14, q: 'A cylinder of curved surface area 1250 m^2 is formed from a rectangular metallic sheet. Find the dimensions of the rectangular sheet if its length is double its breadth.', need: ['50', '25'] },
        { id: 'c14.q8', ch: 14, q: 'Diameter and length of a roller are 84 cm and 120 cm respectively. In how many revolutions can the roller level a playground of area 1584 m^2?', any: ['500'] },
        { id: 'c14.q9', ch: 14, q: 'Water is pouring into a reservoir at the rate of 60 litres per minute. If the volume of the reservoir is 108 m^3, find the number of hours it will take to fill the reservoir.', any: ['30'] },
        { id: 'c14.q10', ch: 14, q: 'An iron pipe is 21 m long and its exterior diameter is 8 cm. If the thickness of the pipe is 1 cm and iron weighs 8 g/cm^3, find the weight of the pipe.', any: ['369.6', '369600'] },
        { id: 'c14.q11', ch: 14, q: 'A well is dug 20 m deep and it has a diameter of 7 m. The earth dug out is spread evenly on a rectangular plot 22 m long and 14 m broad. What is the height of the platform formed?', any: ['2.5'] },
        { id: 'c14.q12', ch: 14, q: 'The volume of a right circular cylinder is 448 pi cm^3 and height 7 cm. Find its lateral surface area and total surface area.', need: ['352', '753.6'] },
        { id: 'c14.h1', ch: 14, q: 'In a cylindrical pipe the area of the top circle is 154 sq units and the curved surface area is 880 sq units. Find the radius and height of the cylinder.', need: ['7', '20'] },
        { id: 'c14.h2', ch: 14, q: 'The length of a room is 50 per cent more than its breadth. The cost of carpeting the room at Rs 38.50 per m^2 is Rs 924 and the cost of painting the walls at Rs 5.50 per m^2 is Rs 1320. Find the dimensions of the room.', need: ['6', '4', '12'] },

        /* ── CH 15 · Statistics & Probability ──────────────────────────── */
        { id: 'c15.m1', ch: 15, q: 'A survey of 100 people found that 20 of them played badminton. In a pie chart, what would be the sector angle of this group? (i) 20 (ii) 36 (iii) 72 (iv) 200', opt: 'iii', any: ['72'] },
        { id: 'c15.m2', ch: 15, q: 'Representing data graphically in the form of rectangles with no gap between successive rectangles is called (i) bar graph (ii) histogram (iii) pie-chart (iv) histogram', opt: 'iv', any: ['histogram'] },
        { id: 'c15.m3', ch: 15, q: 'What is the probability of getting a king if a card is drawn from a pack of 52 cards? (i) 1/52 (ii) 2/52 (iii) 3/52 (iv) 4/52', opt: 'iv', any: ['4/52', '1/13'] },
        { id: 'c15.m4', ch: 15, q: 'A histogram has (i) frequencies as heights (ii) class intervals as heights (iii) frequencies as bases (iv) frequencies as both bases and heights', opt: 'i', any: ['frequencies as heights', 'frequencies as height'] },
        { id: 'c15.m5', ch: 15, q: 'The possible number of outcomes if a coin is tossed twice are (i) one (ii) two (iii) three (iv) four', opt: 'iv', any: ['four', '4'] },
        { id: 'c15.b1', ch: 15, q: "A letter is chosen from the word 'PROBABILITY'. What is the probability that it is a vowel?", any: ['4/11'] },
        { id: 'c15.b2', ch: 15, q: 'Heights of 20 saplings in a nursery (in cm) are: 80, 79, 102, 90, 94, 124, 111, 87, 88, 103, 72, 126, 125, 88, 98, 96, 127, 128, 74, 80. Find the range of their heights.', any: ['56'] },
        { id: 'c15.b3', ch: 15, q: 'A number is selected at random from the first ten natural numbers. What will be the probability of the number being prime?', any: ['2/5', '4/10'] },
        { id: 'c15.b4', ch: 15, q: 'A survey of 180 children on story books gave a pie chart in which adventure is 20%. Find the number of children who read adventure books.', any: ['36'] },
        { id: 'c15.b5', ch: 15, q: 'In a pie chart of story books of 180 children, 10% do not read story books at all. What fraction of children do not read story books at all?', any: ['1/10'] },
        { id: 'c15.q5', ch: 15, q: 'A pie chart shows money spent on sports: football 50 degrees, hockey 100 degrees, cricket 160 degrees. If the total money spent on football is Rs 5000, find (i) total amount spent on sports (ii) money spent on hockey (iii) how much more is spent on cricket than hockey.', need: ['36000', '10000', '6000'] },
        { id: 'c15.q7i', ch: 15, q: 'When a die is thrown, list the outcomes of the event of getting a prime number.', any: ['2, 3, 5', '2,3,5'] },
        { id: 'c15.q7ii', ch: 15, q: 'When a die is thrown, list the outcomes of the event of getting a composite number.', any: ['4, 6', '4,6'] },
        { id: 'c15.q7iii', ch: 15, q: 'When a die is thrown, list the outcomes of the event of getting a number less than 4.', any: ['1, 2, 3', '1,2,3'] },
        { id: 'c15.q8i', ch: 15, q: 'Slips with numbers 1, 15, 9, 7, 18, 48, 73, 6, 36, 4 are mixed in a bag. You pick one slip. What is the probability of getting an even number?', any: ['1/2'] },
        { id: 'c15.q8ii', ch: 15, q: 'Slips with numbers 1, 15, 9, 7, 18, 48, 73, 6, 36, 4 are mixed in a bag. What is the probability of getting a multiple of 3?', any: ['3/5'] },
        { id: 'c15.q8iii', ch: 15, q: 'Slips with numbers 1, 15, 9, 7, 18, 48, 73, 6, 36, 4 are mixed in a bag. What is the probability of getting a multiple of 3 but not 9?', any: ['3/10'] },
        { id: 'c15.q8iv', ch: 15, q: 'Slips with numbers 1, 15, 9, 7, 18, 48, 73, 6, 36, 4 are mixed in a bag. What is the probability of getting a factor of 36?', any: ['3/5', '6/10'] },
        { id: 'c15.q8v', ch: 15, q: 'Slips with numbers 1, 15, 9, 7, 18, 48, 73, 6, 36, 4 are mixed in a bag. What is the probability of getting a one-digit number?', any: ['1/2'] },

        /* ── CH 16 · Rotational Symmetry ───────────────────────────────── */
        { id: 'c16.m2', ch: 16, q: "Letter 'I' has rotational symmetry of order (i) 1 (ii) 2 (iii) 3 (iv) 4", opt: 'ii', any: ['2'] },
        { id: 'c16.m3', ch: 16, q: 'The angle of rotation of a figure is 36 degrees, so its order of rotational symmetry is (i) 1 (ii) 9 (iii) 10 (iv) infinite', opt: 'iii', any: ['10'] },
        { id: 'c16.m4', ch: 16, q: 'A regular pentagon has rotational symmetry of order (i) 2 (ii) 4 (iii) 5 (iv) 3', opt: 'iii', any: ['5'] },
        { id: 'c16.m5', ch: 16, q: 'A figure that looks exactly the same after a half turn (like an S-shaped hexagon) has what angle of rotation? (i) 90 (ii) 180 (iii) 270 (iv) 360', opt: 'ii', any: ['180'] },
        { id: 'c16.b1', ch: 16, q: 'Name two letters of the English alphabet which have no rotational symmetry.', any: ['f', 'g'] },
        { id: 'c16.b3', ch: 16, q: 'Which letters of the English alphabet have rotational symmetry of order 2?', any: ['h', 'n', 'o', 's', 'x', 'z'] },
        { id: 'c16.b4', ch: 16, q: 'Does an isosceles triangle exhibit rotational symmetry? Give reason.', any: ['no'] },
        { id: 'c16.q2', ch: 16, q: 'Name one figure each having rotational symmetry of order 4, 2, 3 and 6, and write the angle of rotation of each.', need: ['square', 'rectangle', 'equilateral triangle', 'hexagon'] },
        { id: 'c16.q3', ch: 16, q: "In the word 'MATHS' which letters show rotational symmetry of order 2?", any: ['h', 's'] },
        { id: 'c16.q4', ch: 16, q: 'List two letters of the English alphabet which exhibit both line as well as rotational symmetry.', any: ['h', 'i', 'o', 'x'] },
        { id: 'c16.q5iii', ch: 16, q: 'Find the angle of rotation of a regular five-pointed star.', any: ['72'] }
    ];

    if (typeof module !== 'undefined' && module.exports) module.exports = BANK;
    if (typeof window !== 'undefined') window.BT_BANK = BANK;
})(this);
