/* ═══════════════════════════════════════════════════════════════════════════
   BitBot KNOWLEDGE EXPANSION v9 — the ~1-crore-parameter upgrade.
   Part 1: DEEP website knowledge (scraped from the live bittuhere.github.io),
   Part 2: more Science, SST, ICT, Maths-concepts,
   Part 3: QUESTION-TEMPLATE expansion (every topic × 6 question forms).
   Loaded AFTER data2.js; pushes into the same INTENTS/QUIZ arrays.
   ═══════════════════════════════════════════════════════════════════════════ */
(function (root) {
    'use strict';
    var BitData = (typeof module !== 'undefined' && module.exports) ? require('./data.js') : root.BitData;
    var INTENTS = BitData.INTENTS;
    var QUIZ = BitData.QUIZ;

    /* ══════════ WEBSITE KNOWLEDGE (bittuhere.github.io — verified from the live site) ══════════ */
    INTENTS.push({ tag: "site_categories", patterns: ["what are the main sections of the site","site categories","what can i choose in the menu","main menu options","study multiplayer singleplayer contact","which categories are there on arcade hub","site ke main section","home page menu kya hai","what is on the home screen","select a category screen"],
        responses: ["🗂️ **Arcade Hub's 4 main doors** (the 'Select a Category' screen):\n1. 📚 **Study** — Fair Copies (official exam copies & study material) + the Weekly Quiz (Class 8 · Maths & Science)\n2. ⚔️ **Multiplayer Games** — play LIVE with friends: Tic Tac Toe Online, Car Game 3D, ArcadeCraft\n3. 🕹️ **Singleplayer Games** — 10 arcade classics with leaderboards: Real City Drift, Pac-Man Reworked, Flappy Bird, Dino, Snake, Tic Tac Toe, RPS, Rock Paper Scissors, ArcadeCraft…\n4. 📧 **Contact Us** — help & feedback form\n\nEvery screen has a **← Back to Menu** button. Lost? Tap it! 🧭"] });
    INTENTS.push({ tag: "site_google_login", patterns: ["login with google","continue with google","google sign in","can i signup using google","google account login","sign in options","login kaise karein google se","google se account banaye"],
        responses: ["🔐 **Login options on the LOGIN screen:**\n- **Email + password** — the classic 'ENTER' way\n- **CONTINUE WITH GOOGLE** — one tap with your Google account ✅\n- New here? → **'Create ID'** link makes your account\n- Forgot password? → **'Trouble signing in? Click here'** opens the reset flow (email code → new password)\n\nAfter signing up you may see **VERIFY EMAIL** (enter the code sent to you, 'Resend code' if it's slow) and **COMPLETE PROFILE**. Then the arcade opens! 🎮"] });
    INTENTS.push({ tag: "site_quiz_rules", patterns: ["weekly quiz rules","quiz rules explained","how does the weekly quiz work in detail","quiz time limit","how many questions in weekly quiz","quiz one attempt","quiz resets when","quiz attempt rules","weekly quiz ke niyam","quiz me kitne question hote hain"],
        responses: ["📋 **Weekly Quiz — official rules (read them, they're strict!):**\n- **20 questions** · Class 8 Maths & Science (D.A.V. school syllabus)\n- ⏱️ **60 seconds per question** — timeout auto-skips\n- 📅 Same 20 questions for EVERYONE this week · **resets every Monday** (questions + options reshuffled weekly)\n- 🔒 **ONE attempt per week** — your score improves only if you do better\n- 🏆 Leaderboard ranks by **fastest total time** (only correct answers count)\n- 🥇 Top 3 each week earn **Gold/Silver/Bronze medals** on their profile\n- 🚫 Tab-switching, minimizing or opening DevTools = **instant ban** (1st cheat: 2 hours; each extra: +1 min). Leaving <60s and returning = treated as accidental, no ban\n- Read the rules screen and tap **'I UNDERSTAND — START QUIZ'** (there's a 5-second read timer!)\n\nFair play = fast play. Good luck! 🍀"] });
    INTENTS.push({ tag: "site_quiz_ban", patterns: ["quiz ban","why am i banned from quiz","cheat detected in quiz","quiz me ban kyu laga","tab switch ban","quiz cancelled cheating","how long is quiz ban","devtools quiz ban","ban lift kab hoga"],
        responses: ["🚫 **'CHEAT DETECTED' — here's the deal:**\nThe weekly quiz watches for **tab switches, minimizing, or DevTools** during your attempt. If caught: the quiz is CANCELLED and you get a ban.\n\n**Ban math:**\n- 1st offence → **2 hours**\n- Every extra offence → **+1 minute** added\n- Ban lifts **automatically** (the screen shows the countdown)\n- Accidental? Leave for **<60 seconds** and return → no ban 🙂\n\nWhy so strict? Everyone gets the same 20 questions — googling answers would wreck the leaderboard for honest players. Play clean, rank high! 🏆"] });
    INTENTS.push({ tag: "site_medals", patterns: ["quiz medals","how to get gold medal","silver bronze medal","medals on profile","medal kaise milega","trophy on profile","top 3 quiz reward","profile me medal"],
        responses: ["🏅 **Quiz Medals — wearable bragging rights:**\nEvery week the **top 3 fastest players** (correct answers, fastest total time) win:\n- 🥇 **Gold** · 🥈 **Silver** · 🥉 **Bronze**\n\nThey shine on your **profile page** under 'QUIZ MEDALS' for everyone to see. Medals reset the race every Monday — so a new week = a fresh shot at gold!\n\nStrategy tip: speed matters as much as accuracy — the leaderboard sorts by TOTAL TIME, so know your Class 8 Maths & Science cold ⚡📚"] });
    INTENTS.push({ tag: "site_username_change", patterns: ["username change request","can i change username","username badalna hai","how often can i change username","username change rules","request username change"],
        responses: ["✏️ **Username change — the rules:**\n- It's a **REQUEST**, not instant: Profile → ⚙️ Account → **'Request Username Change'** → type the new name → admin reviews and renames it manually\n- Allowed **once per 7 days** ⏳\n- The admin's rename tool migrates EVERYTHING with you: profile, friends, chats, scores, medals, quiz data — nothing is lost\n\nPick wisely, you've got a week of cooldown after each change! 😄"] });
    INTENTS.push({ tag: "site_bio", patterns: ["about me section","profile bio","add a bio","bio character limit","about me likhna hai","profile description","tap to add a bio","bio me kya likhe"],
        responses: ["💬 **The 'About Me' bio (on your profile):**\n- Tap **'Tap to add a bio…'** → type your line → SAVE\n- Limit: **100 characters** — short, punchy, legendary\n- It shows on your profile card next to your stats (friends, best score, games played)\n\nIdeas: 'Snake main 🐍, leaderboard se bhaag!' · 'Pac-Man dot collector' · 'Fair Copies topper, quiz hopper' · 'Munger ka gamer ⚡'\n\n100 chars is all you need to be memorable 😎"] });
    INTENTS.push({ tag: "site_contact_form", patterns: ["contact form","how to contact the developer","attach file in contact","message the admin","contact page kaise use karein","feedback form","report a problem to admin","contact us section","email the developer","max attachment size"],
        responses: ["📧 **Contact Us — talking to the humans behind Arcade Hub:**\nThe form asks for:\n1. **Your Email** (so the reply finds you)\n2. **Subject** (what's it about?)\n3. **Message** (details, details!)\n4. **Attach File** — optional, **max 5 MB**, tap OR drag-and-drop (screenshots of bugs are gold 📸)\n\nHit **SEND MESSAGE** → you'll see the 'MESSAGE SENT' screen with sending status, and it auto-redirects back to the hub in ~10 seconds.\n\nBugs, feature ideas, Fair Copies requests, or just saying hi — this form is THE way. The dev reads it! 👀"] });
    INTENTS.push({ tag: "site_admin_features", patterns: ["what can admin do","admin panel features","admin control panel","admin dashboard","admin tools","admin kya kar sakta hai","announce to all users","admin delete user","admin quiz management"],
        responses: ["⚡ **ADMIN CONTROL — behind the ⛔ curtain (for the dev's eyes):**\nThe admin panel (login → '⚠ ADMIN PANEL') has 9 desks:\n- 📊 **Dashboard** — site stats at a glance\n- 👥 **Users** — view all accounts · ✏️ **Rename** (migrates profile/friends/chats/scores/medals/quiz data to the new key) · 🗑️ **Delete** (permanent — account, friends, status, invites, everything)\n- 🏆 **Scores** — VIEW / RESET / SET any player's scores per game (Flappy 🐦 Dino 🦕 Snake 🐍 Pac-Man ᗧ)\n- 📢 **Announce** — global announcements pushed to ALL users 🔔\n- ✉️ **DM** — private message any player\n- 🏠 **Rooms** — see live multiplayer rooms, refresh, clean empty ones\n- 🧠 **Quiz** — leaderboard, weekly reset, and **SET WEEKLY SPECIAL QUESTION** (pick correct option A/B/C/D)\n- 🟢 **Online** — who's playing right now\n\nWith great power comes great responsibility — that's why it needs admin credentials! 🔐"] });
    INTENTS.push({ tag: "site_rotate", patterns: ["rotate your device","landscape mode","tap to rotate","screen rotation message","phone rotate karo","best experience rotate","why does it say rotate my phone"],
        responses: ["📱 **'TAP TO ROTATE' — nothing's broken!**\nSome screens (especially games) show a rotate prompt: **'For the best experience, please rotate your device to landscape'** 🔄\n\n- **Landscape** = phone sideways (wide like a TV) — that's how the arcade games are designed\n- Just turn your phone (or tap the 🔄 button if auto-rotate is off in your phone settings)\n- Chat, profile & study pages work fine in portrait too\n\nWider screen = more game. Rotate and race! 🏎️"] });
    INTENTS.push({ tag: "site_rank", patterns: ["your rank not ranked","what is my rank","rank kaise badhaye","how do ranks work here","not ranked meaning","get ranked","rank widget","my rank shows not ranked"],
        responses: ["📈 **'YOUR RANK: Not ranked' → time to fix that!**\nThe rank card tracks where you stand against other players.\n\n**How to get ranked & climb:**\n1. 🎮 Play the leaderboard games — Flappy, Dino, Snake, Pac-Man — your BEST scores feed the rankings\n2. 🧠 Crush the Weekly Quiz — it's ranked by fastest total time, top 3 even win medals\n3. 🔁 Keep improving — scores sync when you're online\n\nCheck the 🏆 **Leaderboard** page (tabs per game) to see the TOP PLAYERS and exactly what you're chasing. From 'Not ranked' to #1 is just one great run away ⚡"] });
    INTENTS.push({ tag: "site_invite", patterns: ["friend invite join decline","someone invited me","invite popup","accept friend request","join or decline invite","friend request kaise accept kare","invite notification","multiplayer invite"],
        responses: ["🤝 **Invites — JOIN or DECLINE:**\nWhen a friend invites you (to be friends or into a multiplayer room), a popup slides in:\n- ✅ **JOIN** — accept instantly (you're in the room / friends list)\n- ✗ **DECLINE** — politely skip; nothing breaks, you can be invited again\n\nFriend invites also live in the 👥 **Friends** page (search a player → GO → add). And the 🔔 bell shows **Global** announcements vs **Private** messages.\n\nMultiplayer tip: invites are how Tic Tac Toe Online, Car Game 3D and ArcadeCraft battles start — JOIN fast, opponents hate waiting 😄"] });
    INTENTS.push({ tag: "site_fair_copies_drive", patterns: ["fair copies drive","open in drive","google drive folder","exam copies download","fair copies google drive","study material drive link","open in drive button","copies drive me kaise khole"],
        responses: ["📚 **Fair Copies + Google Drive:**\nThe Study → 📝 **Fair Copies** section shows official exam copies & study material in the built-in reader — and there's an **'🧭 Open in Drive'** button that opens the full **Google Drive folder** with everything.\n\n**Why use Drive?**\n- Browse/download ALL files (not just the featured ones)\n- Opens in the Google Drive app if installed\n- Great on slow connections — Drive handles the heavy lifting\n\nThe in-page reader is best for quick revision; Drive is the full library. Both free, both official ✅"] });
    INTENTS.push({ tag: "site_leaderboard_tabs", patterns: ["leaderboard games list","which games are on the leaderboard","leaderboard tabs","flappy dino snake pacman leaderboard","leaderboard me kaun se game","score ranking games"],
        responses: ["🏆 **The Leaderboard — 5 ranking tabs:**\n🐦 **Flappy** · 🦕 **Dino** · 🐍 **Snake** · ᗧ **Pac-Man** · 🧠 **Quiz**\n\n- Tap a game tab → TOP PLAYERS ranked by best score\n- The 🧠 Quiz tab is different: ranked by **fastest total time** with correct answers, resets weekly\n- Scores sync only when online (offline play = '⚡ You're offline — scores won't sync')\n- Your profile shows your **Best Score** & **Games Played** stats\n\nFour reflex games + one brain game. Which tab will carry your name? 😏"] });
    INTENTS.push({ tag: "site_offline_banner", patterns: ["you are offline banner","offline tap to retry","scores wont sync","multiplayer offline","offline warning message","net chala gaya banner","why does it say im offline"],
        responses: ["⚡ **'You're offline — Multiplayer & scores won't sync. Tap to retry.'**\nThat banner is the site being honest, not broken:\n- 📴 **Offline you CAN:** browse pages the service worker cached, chat with me (BitBot runs fully offline!), read cached Fair Copies\n- 🚫 **Offline you CAN'T:** play multiplayer rooms, send chats/friend requests, or save NEW highscores to the leaderboard\n- 👆 **Tap the banner** to retry the connection instantly\n\nWhen you're back online, everything syncs. Pro move: enable push notifications so announcements reach you even when the site is closed 🔔"] });
    INTENTS.push({ tag: "site_change_password_flow", patterns: ["change password steps","how to change my password","password change verify","current password new password","forgot password reset code","password bhool gaya reset","reset password email code","min 4 chars password"],
        responses: ["🔑 **Password flows (both on the site):**\n\n**Change password (you know the old one):**\nProfile → Change Password → **STEP 1 OF 2 — VERIFY IDENTITY**: enter Current Password → Verify → **STEP 2**: New Password (**min 4 chars**) + Confirm → done ✅\n\n**Forgot password (reset via email):**\nLogin screen → **'Trouble signing in? Click here'** → 🔑 RESET PASSWORD → enter your email → **SEND CODE** → type the code from your email → set new password → back in the game 🎮\n\nSafety: don't reuse your school-email password here, and NEVER share any code — not even with 'admin' DMs. Real admins never ask for codes 🛡️"] });
    INTENTS.push({ tag: "site_profile_stats", patterns: ["profile page shows what","my profile stats","friends best score games played","profile kya dikhata hai","what is on my profile","profile card info","quiz medals section profile"],
        responses: ["👤 **Your profile page — the full tour:**\n- **Your name + rank** ('Not ranked' until you climb!)\n- 👥 **Friends** count → opens the friends list & chat\n- 🏆 **Best Score** — your personal record across games\n- 🎮 **Games Played** — your session count\n- 💬 **About Me** bio (tap to add, 100 chars)\n- 🏅 **QUIZ MEDALS** — gold/silver/bronze from weekly top-3 finishes\n- ⚙️ **Account** — logout, change password, **Request Username Change** (once/7 days)\n- 🔔 **Notifications** — enable push so announcements & messages reach you like a real app\n- 🔍 **Search Player** — find anyone by username → GO\n\nIt's your arcade identity card. Make it legendary! ⚡"] });

    /* ══════════ SCIENCE — deeper batch ══════════ */
    INTENTS.push({ tag: "sci_genetics", patterns: ["what is genetics","heredity","what is dna","genes and chromosomes","dominant recessive traits","gregor mendel","why do i look like my parents","genetics kya hai","what is a gene","inherited traits examples"],
        responses: ["🧬 **Genetics — why you're a remix of your family:**\n- **DNA** = the instruction manual in (almost) every cell — a twisted ladder (double helix) written in 4 chemical letters: A, T, G, C. Your full manual = ~3 billion letters!\n- **Gene** = one instruction (e.g., 'eye colour: brown') · **Chromosome** = a packed chapter — humans have **46 (23 pairs)**: half from mom, half from dad\n- **Heredity** = traits passing down. **Dominant** genes shout (brown eyes), **recessive** whisper (blue eyes — needs BOTH copies)\n- **Gregor Mendel** 🌱 — the monk who grew 28,000 pea plants and discovered the rules (1860s) — 'Father of Genetics'\n- Fun: your DNA is 99.9% identical to every human — and ~60% shared with a BANANA 🍌. Unique AND connected!"] });
    INTENTS.push({ tag: "sci_cell_division", patterns: ["cell division","mitosis","meiosis","how do cells multiply","difference between mitosis and meiosis","cell cycle","why do cells divide","koshika vibhajan","how does a cut heal","growth and cell division"],
        responses: ["🔬 **Cell division — how 1 cell became YOU (30+ trillion of them):**\n\n**Mitosis (body cells):** 1 cell → 2 IDENTICAL copies\n1. Chromosomes duplicate · 2. line up in the middle · 3. pull apart to opposite ends · 4. cell pinches into two\n→ Used for **growth & repair** — that's how a cut heals and how you got taller 📏\n\n**Meiosis (sex cells only):** 1 cell → 4 cells with HALF the chromosomes (23 each)\n→ Makes sperm & egg cells; when they combine: 23+23 = 46 — a brand-new unique human! It even SHUFFLES genes (crossing over), so siblings differ (except identical twins)\n\nOne fertilized egg → ~200+ rounds of division → you. Cell division = life's copy-paste, with an occasional beautiful typo called evolution 🧬"] });
    INTENTS.push({ tag: "sci_adolescence", patterns: ["adolescence","puberty","changes during puberty","what is puberty class 8","reaching age","voice change in boys","menstruation basics","hormones in adolescence","height growth spurt","kishoravastha"],
        responses: ["🌱 **Adolescence ('Reaching Age', Class 8 science — the honest, scientific version):**\n- **Adolescence** = the bridge from child to adult, roughly **10–19 years**. Your body runs a hormone-driven upgrade 📶\n- **Changes in everyone:** growth spurt (height!), body shape changes, oilier skin (hello, pimples), more sweating, mood swings, brain rewiring (better reasoning, bigger feelings)\n- **Boys:** voice deepens (voice box grows → 'Adam's apple'), facial/body hair, shoulders broaden\n- **Girls:** hips widen, breasts develop, **menstruation** begins — a healthy monthly cycle where the uterus lining sheds (blood + tissue) if there's no pregnancy. It's biology, not embarrassment — it means the body works correctly ✅\n- **Hormones** = chemical messengers: testosterone (boys), estrogen (girls), growth hormone (everyone)\n- **Survival tips:** daily bath, iron-rich food during periods, sleep 8-9h (growth happens while sleeping!), talk to parents/teachers/doctors with questions — that's what they're for\n\nEveryone goes through it at their own pace. Early, late, or in-between = all normal 🌈"] });
    INTENTS.push({ tag: "sci_stars", patterns: ["what is a star","how do stars shine","life cycle of a star","what is a galaxy","milky way galaxy","what is a light year","types of stars","supernova","neutron star","tare kya hote hain","why do stars twinkle"],
        responses: ["⭐ **Stars — the universe's fusion reactors:**\n- A star = a giant ball of gas (mostly hydrogen) crushing itself under gravity until the core ignites **nuclear fusion**: hydrogen → helium + ENORMOUS light/heat. Our Sun fuses ~600 million tonnes of hydrogen PER SECOND ☀️\n- **Life cycle:** nebula (gas cloud) → protostar → main-sequence star (like the Sun, ~10 billion years) → red giant → **white dwarf** (Sun's fate) — but massive stars go dramatic: **supernova** explosion 💥 → **neutron star** (a sugar-cube of it weighs 1 billion tonnes!) or **black hole**\n- **Galaxy** = a city of stars — ours, the **Milky Way**, holds 100–400 BILLION stars and you're seeing its edge as that milky band at night 🌌\n- **Light year** = DISTANCE light travels in a year (~9.46 trillion km). The nearest star (Proxima Centauri) is 4.2 light years away — its light left before your great-grandparents were born\n- **Twinkling** = Earth's turbulent air bending starlight. Astronauts see steady stars!"] });
    INTENTS.push({ tag: "sci_universe", patterns: ["the universe","big bang theory","how did the universe begin","what is a black hole","age of the universe","universe kitna bada hai","cosmos","is the universe expanding","event horizon","singularity"],
        responses: ["🌌 **The Universe — everything, everywhere:**\n- **Age:** ~**13.8 billion years**, begun (as far as we know) in the **Big Bang** — not an explosion IN space, but space itself expanding from an ultra-hot dense state. Evidence: galaxies flying apart (redshift) + leftover 'baby universe' radiation everywhere (CMB)\n- **Scale:** ~2 trillion galaxies · our Milky Way is one of them · Earth is speck #3 around an average star 😵\n- **Black holes** = gravity so strong that inside the **event horizon**, nothing escapes — not even light. Made from collapsed giant stars (and monster ones sit in galaxy centers — Sagittarius A* in ours = 4 million suns!). We PHOTOGRAPHED one in 2019 (M87*) 📸\n- The universe is still **expanding** — and accelerating (blame 'dark energy', which with 'dark matter' makes up ~95% of everything… that we can't see. Astronomers stay humble 🙃)\n- Time near a black hole slows down — yes, like Interstellar. Physics is wilder than movies!"] });
    INTENTS.push({ tag: "sci_mirrors", patterns: ["reflection of light","types of mirrors","concave convex mirror","plane mirror image","mirror image laterally inverted","where are concave mirrors used","darpan ke prakar","why is ambulance written reversed","mirror formula basics"],
        responses: ["🪞 **Mirrors & reflection — light's boomerang:**\n\n**Laws of reflection:** (1) angle of incidence = angle of reflection (2) incoming ray, reflected ray and the normal all lie in one plane. Simple, non-negotiable ✅\n\n**Three mirror types:**\n- **Plane** (flat, your bathroom mirror) — image: same size, upright, **laterally inverted** (left↔right swap — that's why AMBULANCE is written reversed, so drivers see it correctly in THEIR mirror! 🚑)\n- **Concave** (caved in) — the magic one: close-up = big upright image (shaving/makeup/dentist mirrors), far = real inverted image (torch & headlight reflectors, telescope mirrors, solar furnaces)\n- **Convex** (bulging out) — always small, upright, WIDE view → vehicle side-mirrors ('objects in mirror are closer than they appear!' 🚗), shop security mirrors\n\nFun: periscopes use two plane mirrors at 45°; kaleidoscopes use three. Reflection = why you exist in mirrors at all — photons bouncing off you, then the glass, then your eye ✨"] });
    INTENTS.push({ tag: "sci_lenses", patterns: ["refraction of light","lenses concave convex","why does a pencil look bent in water","myopia hypermetropia","nearsightedness farsightedness","how do spectacles work","lens used in magnifying glass","refraction kya hai","prism splits light","power of a lens"],
        responses: ["🔍 **Lenses & refraction — light bending to your will:**\n- **Refraction** = light CHANGING direction when it enters a new medium (air→water→glass) because its speed changes. That's why a pencil looks bent in a glass of water, and pools look shallower than they are 🏊\n- **Convex lens** (thick middle, 'magnifying') — converges light → magnifying glasses, cameras, eyes!, microscopes, telescopes\n- **Concave lens** (thin middle) — diverges light → peepholes, spectacle corrections\n- **Your EYE has a convex lens** — it focuses light on the retina (the screen at the back)\n\n**Vision defects & fixes:**\n- **Myopia (near-sighted):** see near fine, far blurry → image forms BEFORE retina → fixed with **concave** spectacles 👓\n- **Hypermetropia (far-sighted):** near blurry → image would form BEHIND retina → fixed with **convex** lenses\n- **Cataract** = cloudy lens → replaced surgically (one of medicine's greatest fixes!)\n\nBonus: a **prism** refracts each colour by a different amount → splits white light into VIBGYOR 🌈. Newton's favourite party trick."] });
    INTENTS.push({ tag: "sci_pressure", patterns: ["buoyancy","archimedes principle","why do ships float","why does a needle sink but ship float","upthrust","pressure in liquids","atmospheric pressure","why are bag straps wide","pressure force area"],
        responses: ["⚓ **Pressure & buoyancy — why steel ships float:**\n- **Pressure = Force ÷ Area** (Pascal, Pa). Same force, smaller area = MORE pressure — that's why knives are sharp, nails pointy, and school-bag straps WIDE (big area = gentle on shoulders 🎒)\n- **Liquids push too:** pressure grows with depth (dam walls are thicker at the bottom!) and pushes equally in all directions\n- **Atmospheric pressure:** the entire sky sits on you — ~101 kPa at sea level! You don't flatten because your body pushes back equally. Drinking with a straw = you remove air, atmosphere PUSHES the drink up 🥤\n- **Buoyancy/Upthrust:** water pushes UP on anything in it. **Archimedes' principle** (shouted as 'Eureka!' from a bathtub 🛁): upthrust = weight of the liquid DISPLACED\n- **The ship paradox:** a steel needle sinks (displaces tiny water = tiny upthrust). A steel SHIP is hollow — its bowl shape displaces TONNES of water → huge upthrust → floats! Submarines float/sink on demand by flooding or emptying ballast tanks 🌊\n- Ice floats (less dense than water), hot-air balloons rise (less dense than air) — same density story everywhere!"] });
    INTENTS.push({ tag: "sci_static", patterns: ["static electricity","lightning","why do clothes stick in winter","electric charge","earthing","lightning conductor","what causes lightning","spark when removing sweater","positive negative charges","static bijli"],
        responses: ["⚡ **Static electricity & lightning — sparks of imbalance:**\n- Everything is made of atoms with + (protons) and − (electrons) charges. Rub two things together and electrons JUMP ship → one object becomes negative, the other positive → **static charge**\n- Opposites attract: that's the sweater-crackle in winter, balloons sticking to walls, comb-picking-up-paper tricks, and clothes clinging in the dryer 👕\n- **Lightning** = static on a MONSTER scale: storm clouds grind ice particles until the cloud bottom goes hugely negative → the ground below goes positive → when the gap can't hold, the air itself breaks down and ZAP — a giant spark at ~30,000°C (5× hotter than the Sun's surface!) 🌩️ Thunder = the sonic boom of that superheated air\n- **Earthing** = giving excess charge a path to the ground (that third pin in your plug!) · **Lightning conductors** = metal rods on buildings that politely escort the bolt to earth\n- Safety: inside a building/car during storms = safe; under a tree = the WORST idea. Count flash→boom seconds ÷3 = storm distance in km ⏱️"] });
    INTENTS.push({ tag: "sci_work_power", patterns: ["work in physics","what is power in physics","joule and watt","formula for work","work energy power class 9","unit of power","when is work done","work force displacement","1 watt means","power ka formula"],
        responses: ["🏋️ **Work, Energy & Power — physics' accountancy:**\n- **WORK** is done ONLY when a force MOVES something: **W = F × d** (force × displacement). Pushing a wall for an hour? Zero work (physics is heartless 😄). Unit: **joule (J)** = 1 newton × 1 metre\n- **ENERGY** = the capacity to do work (also joules). Kinetic = ½mv² · Potential (gravity) = mgh\n- **POWER** = how FAST work happens: **P = W ÷ t**. Unit: **watt (W)** = 1 joule per second. Two climbers reach the same roof — same work — but the sprinter used more POWER 🏃\n- Scale feel: you climbing stairs ≈ 200-400 W · old bulb = 60 W · LED bulb = 9 W (same light, ⅙ the power!) · microwave ≈ 1000 W · your 'electricity bill unit' = **1 kWh** = 3.6 million joules\n- 1 horsepower ≈ 746 W (James Watt needed a way to sell steam engines against horses 🐴)\n\nWork-energy theorem: net work done = change in kinetic energy. Physics in one line!"] });
    INTENTS.push({ tag: "sci_carbon", patterns: ["carbon compounds","organic chemistry","what is a hydrocarbon","why is carbon special","covalent bonds","diamond and graphite","saturated unsaturated compounds","methane ethane","carbon ke yauugik","what are alkanes alkenes"],
        responses: ["💎 **Carbon — the LEGO atom of life:**\n- Why carbon rules: it has **4 outer electrons** → forms 4 strong **covalent bonds** (sharing electrons) with other atoms AND with itself → chains, rings, branches — millions of compounds (more than all other elements combined!)\n- **Hydrocarbons** = carbon + hydrogen only:\n  · **Alkanes** (single bonds, 'saturated'): methane CH₄ (cooking gas!), ethane, propane, butane (LPG) 🔥\n  · **Alkenes** (a double bond, 'unsaturated'): ethene — ripens fruits artificially!\n  · **Alkynes** (triple bond): ethyne = welding fuel\n- Same atoms, different arrangement = **allotropes**: **diamond** (tetrahedral network — hardest natural) vs **graphite** (flat slippery sheets — pencil 'lead' & lubricant) — both pure carbon! ✏️💎\n- Fuels (petrol, CNG) = hydrocarbons; burning them = C+H meeting O₂ → CO₂ + H₂O + energy\n- Everything alive — sugar, DNA, proteins, YOU — is carbon-based. Silicon dreams, carbon does 🧪"] });
    INTENTS.push({ tag: "sci_plastics", patterns: ["plastics and polymers","what is a polymer","thermoplastics thermosetting","why is plastic bad for environment","types of plastic","polythene","biodegradable plastic","plastic recycling codes","plastic kyun nuksandeh hai","bakelite melamine"],
        responses: ["🥤 **Plastics & polymers — long molecular chains:**\n- **Polymer** = 'many parts' — a giant molecule of repeating units (monomers) linked like a chain. Natural ones exist: cotton (cellulose), wool (protein), rubber!\n- **Synthetic plastics:** polythene (bags), PVC (pipes), PET (bottles — check the ♳ triangle codes!), nylon (fibres), teflon (non-stick)\n- **Thermoplastics** 🔁 — soften on heating, reshape forever (PET, polythene) → RECYCLABLE\n- **Thermosetting** 🔥 — set once, then refuse to melt (bakelite — switches/handles, melamine — unbreakable crockery) → hard to recycle\n- **The problem:** plastic lasts centuries, breaks into **microplastics** (found in oceans, food, even human blood 😬), chokes drains & animals; burning it releases poisons\n- **The fixes:** say no to single-use, carry cloth bags & steel bottles, segregate waste for recycling, and support bioplastics (made from corn/starch — they compost!)\n- Plastic isn't evil — syringes, helmets, water pipes save lives. WASTING it is the evil 🌍"] });
    INTENTS.push({ tag: "sci_combustion", patterns: ["combustion","types of combustion","what is fuel","calorific value","flammable inflammable","how does fire work","fire triangle","how to extinguish fire","aag kaise bujhaye","why is cng better than petrol"],
        responses: ["🔥 **Combustion — the chemistry of fire:**\n- **Combustion** = a substance reacting with oxygen, releasing heat & light. Fuel + O₂ → CO₂ + H₂O + energy\n- **The FIRE TRIANGLE** (all 3 needed): 🔥 fuel + oxygen + heat (ignition temperature). Remove ANY corner → fire dies — that's how firefighting works: water removes heat, a blanket/CO₂ removes oxygen, shutting the gas removes fuel 🧯\n- **Types:** rapid (a candle, burning paper), spontaneous (oily rags self-igniting!), explosion (fireworks, crackers — sudden gas + heat + sound) 💥\n- **Ignition temperature** = the minimum heat a fuel needs to catch fire. **Inflammable** = catches fire EASILY (petrol, LPG, alcohol — confusing word, it does NOT mean 'doesn't burn'!)\n- **Calorific value** = energy per kg (kJ/kg): hydrogen tops (~150,000), CNG beats petrol, wood is low + smoky\n- **Better fuels:** CNG/LPG burn cleaner (less CO & soot); petrol/diesel engines still poison city air\n- **Danger:** incomplete combustion in closed rooms (gensets, coal heaters) makes **carbon monoxide** — the silent killer. Ventilation saves lives 🌬️"] });
    INTENTS.push({ tag: "sci_biodiversity", patterns: ["biodiversity","endangered species","red data book","extinct animals","why protect biodiversity","endemic species","conservation of wildlife","biodiversity kya hai","species extinction","dodo dinosaur extinct"],
        responses: ["🐅 **Biodiversity — Earth's family album:**\n- **Biodiversity** = the variety of ALL life — species, genes, ecosystems. India is one of the world's 17 **'megadiverse'** countries (8% of all recorded species!) 🇮🇳\n- **Endangered** = at risk of extinction: Bengal tiger, one-horned rhino, Asiatic lion (Gir only!), snow leopard, Great Indian Bustard (<150 left 😢), Ganges dolphin\n- **Extinct** = gone forever: dinosaurs, dodo, passenger pigeon, cheetah (from India — now REINTRODUCED from Africa in 2022! 🐆)\n- **Endemic** = found ONLY in one place: lion-tailed macaque (Western Ghats), Kashmir stag\n- **Red Data Book** = the official record of threatened species · **Red List** by IUCN\n- **Why care?** Every species is a thread: bees pollinate ⅓ of our food, forests make rain & oxygen, coral reefs feed oceans, and medicines hide in plants (25% of modern drugs came from plants!)\n- **Protection:** national parks & sanctuaries (Project Tiger 1973 — tigers went 1,827→3,167 📈), biosphere reserves, no-poaching laws, seed banks, and YOU: don't buy wildlife products, plant native trees, spread the word 🌳"] });
    INTENTS.push({ tag: "sci_instruments", patterns: ["scientific instruments","what does a microscope do","telescope types","instruments and their uses","stethoscope barometer thermometer","what is a seismograph","laboratory instruments","scientific devices names","upkaran aur unke upyog","what machine measures humidity"],
        responses: ["🔬 **Scientific instruments — the senses of science:**\n- **Microscope** — makes tiny things big (cells, bacteria); electron microscopes zoom to ATOM scale (2 million×!)\n- **Telescope** — grabs distant light: refracting (lenses, Galileo's), reflecting (mirrors, huge modern ones), and space telescopes like Hubble & James Webb (infrared eyes on the early universe 🔭)\n- **Stethoscope** — amplifies heart/lung sounds 🫀\n- **Thermometer** — temperature · **Barometer** — air pressure (falling = storm coming!) · **Hygrometer** — humidity · **Anemometer** — wind speed · **Rain gauge** — rainfall\n- **Seismograph** — records earthquake waves (Richter scale!)\n- **ECG/EEG** — heart & brain electrical tracings · **X-ray/MRI** — seeing inside bodies\n- **Balance/spring scale** — mass & weight · **Ammeter/voltmeter** — current & voltage · **Multimeter** — both in one\n- **Spectroscope** — splits light to reveal what stars are MADE of (that's how we know the Sun has helium — discovered in the Sun before Earth!)\n- Every instrument = humanity wearing glasses it couldn't before 👓"] });
